// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFile(arg1:string):Promise<string>;

export function AnnounceFile(arg1:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DownloadFile(arg1:string):Promise<void>;

export function GetConfig():Promise<main.ConfigData>;

export function GetConnectedPeers():Promise<Array<main.PeerInfo>>;

export function GetDownloads():Promise<Array<main.DownloadInfo>>;

export function GetInitError():Promise<string>;

export function GetLocalFiles():Promise<Array<main.LocalFileInfo>>;

export function GetNetworkStatus():Promise<main.NetworkStatus>;

export function GetPeerID():Promise<string>;

export function GetStats():Promise<main.StatsData>;

export function GetUploadProgress():Promise<Array<main.UploadProgressInfo>>;

export function IsReady():Promise<boolean>;

export function OpenFileLocation(arg1:string):Promise<void>;

export function RefreshDHT():Promise<void>;

export function SearchByCID(arg1:string):Promise<number>;

export function SearchByText(arg1:string):Promise<Array<main.SearchResult>>;

export function SelectDirectory():Promise<string>;

export function SelectDownloadDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SetDownloadDirectory(arg1:string):Promise<void>;

export function SetMaxUploadRate(arg1:number):Promise<void>;
