// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFile(arg1) {
  return window['go']['main']['App']['AddFile'](arg1);
}

export function AnnounceFile(arg1) {
  return window['go']['main']['App']['AnnounceFile'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConnectedPeers() {
  return window['go']['main']['App']['GetConnectedPeers']();
}

export function GetDownloads() {
  return window['go']['main']['App']['GetDownloads']();
}

export function GetInitError() {
  return window['go']['main']['App']['GetInitError']();
}

export function GetLocalFiles() {
  return window['go']['main']['App']['GetLocalFiles']();
}

export function GetNetworkStatus() {
  return window['go']['main']['App']['GetNetworkStatus']();
}

export function GetPeerID() {
  return window['go']['main']['App']['GetPeerID']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetUploadProgress() {
  return window['go']['main']['App']['GetUploadProgress']();
}

export function IsReady() {
  return window['go']['main']['App']['IsReady']();
}

export function OpenFileLocation(arg1) {
  return window['go']['main']['App']['OpenFileLocation'](arg1);
}

export function RefreshDHT() {
  return window['go']['main']['App']['RefreshDHT']();
}

export function SearchByCID(arg1) {
  return window['go']['main']['App']['SearchByCID'](arg1);
}

export function SearchByText(arg1) {
  return window['go']['main']['App']['SearchByText'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectDownloadDirectory() {
  return window['go']['main']['App']['SelectDownloadDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SetDownloadDirectory(arg1) {
  return window['go']['main']['App']['SetDownloadDirectory'](arg1);
}

export function SetMaxUploadRate(arg1) {
  return window['go']['main']['App']['SetMaxUploadRate'](arg1);
}
